### ISSUE TITLE
Add Ctrl + Tab for iOS navigation

### ISSUE THREAD

**Issue by jamieherrera** [workday-accessibility/accessibility-eval#1]
iOS navigation section should be updated to describe the intended movements (linear vs Tab groups). See Apple Dev Forum thread https://developer.apple.com/forums/thread/747458

- Navigate to the next focusable element | Ctrl + tab
- Navigate to the previous focusable element | ctrl + shift + tab 
- Navigate to the next Tab Group | tab
- Navigate to the previous Tab Group | shift + tab
- Arrow keys move directionally to whatever element can be found in the arrow's direction

Content groups, however, are different than Tab Groups.

**Comment by samogami** [comment]
Thank you for the additional information.  I have updated the document.
